#![no_std]
#![feature(const_refs_to_cell)]
// #![feature(maybe_uninit_uninit_array)]
// #![feature(sync_unsafe_cell)]
// #![feature(type_alias_impl_trait)]
// #![feature(const_maybe_uninit_uninit_array)]
// #![feature(maybe_uninit_slice)]
