[package]
name = "credentials"
version = "1.0.0"
description = "Containes WiFi credentials our bots use to connect."

[lib]
bench = false
path = "src/lib.rs"

[features]
default = []
no-private-credentials = []
