// This file is autogenerated by build.rs

pub const A3: u16 = 880;
pub const AS3: u16 = 830;
pub const B3: u16 = 783;
pub const C3: u16 = 739;
pub const CS3: u16 = 698;
pub const D3: u16 = 659;
pub const DS3: u16 = 622;
pub const E3: u16 = 587;
pub const F3: u16 = 554;
pub const FS3: u16 = 523;
pub const G3: u16 = 493;
pub const A4: u16 = 440;
pub const AS4: u16 = 415;
pub const B4: u16 = 391;
pub const C4: u16 = 369;
pub const CS4: u16 = 349;
pub const D4: u16 = 329;
pub const DS4: u16 = 311;
pub const E4: u16 = 293;
pub const F4: u16 = 277;
pub const FS4: u16 = 261;
pub const G4: u16 = 246;
