[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
# runner = 'probe-run --chip STM32H743ZITx --connect-under-reset --probe 001B00243038510634333935'
runner = 'probe-run --chip STM32H723ZGTx --connect-under-reset'
# runner = 'probe-run --chip STM32H7A3ZITx --connect-under-reset'

[env]
DEFMT_LOG = "trace"
