[package]
name = "ateam-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ateam-common-packets = { path = "../software-communication/ateam-common-packets/rust-lib" }
local-ip-address = "0.4.9"