name: A-Team Firmware
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Validate Nix Envoirnment
        shell: bash
        run: |
          . /github/home/.nix-profile/etc/profile.d/nix.sh
          export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
          nix flake check
      - name: Build Firmware
        shell: bash
        run: |
          . /github/home/.nix-profile/etc/profile.d/nix.sh
          nix develop -c make clean
          nix devleop -c make all

