name: A-Team Firmware
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    container: ros:galactic
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Build Firmware
      shell: bash
      run: |
        nix develop -c make clean
        nix devleop -c make all
    - name: Validate Nix Envoirnment
      shell: bash
      run: |
        export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
        nix flake check

