name: A-Team Firmware
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
jobs:
  test-firmware-build:
    variables:
      GIT_SUBMODULE_STRATEGY: recursive
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config:
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Validate Nix Envoirnment
        shell: bash
        run: |
          nix flake check
          nix develop -c arm-none-eabi-gcc --version
      - name: Build Common Packets
        shell: bash
        run: |
          nix develop -c make software-communication-clean
          nix develop -c make software-communication-build
          nix develop -c make software-communication-test
      - name: Build Stspin Firmware
        shell: bash
        run: |
          nix develop -c make clean
          nix develop -c make stspin-all
      - name: Build Motorboard Firmware
        shell: bash
        run: |
          nix develop -c make clean
          nix develop -c make motorboard-all
