name: A-Team Firmware
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-20.04
    container: ros:galactic
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Nix Environment
        shell: bash
        run: |
          ./util/linux_setup.sh
      - name: Validate Nix Envoirnment
        shell: bash
        run: |
          export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
          nix flake check
      - name: Build Firmware
        shell: bash
        run: |
          nix develop -c make clean
          nix devleop -c make all

